#!/bin/bash
#
# Topfield TF5000PVR hotplug script
#
# Based on script from Jürgen Bausa
#

logger "hotplug $REALNAME: ACTION is $ACTION, DEVICE is $DEVICE, REMOVER is $REMOVER"

case $ACTION in

add)

    # change permissons to allow access for topi group 
    chmod 666 "${DEVICE}"

    # remover script	
    echo "#!/bin/sh" >> $REMOVER
    chmod a+x $REMOVER

    ;;
*)
    debug_mesg toppypvr $ACTION event not supported
    ;;

esac
